//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Depot
    {
        public Inventory_Depot()
        {
            this.Inventory_Transaction = new HashSet<Inventory_Transaction>();
            this.Inventory_Transaction1 = new HashSet<Inventory_Transaction>();
        }
    
        public long ID { get; set; }
        public string TextName { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime NewTime { get; set; }
        public short Del { get; set; }
        public int Company_ID { get; set; }
        public string GuiGe { get; set; }
        public string XingHao { get; set; }
        public string PinPai { get; set; }
        public Nullable<long> GongYingShang_ID { get; set; }
        public string Bak { get; set; }
        public string Number { get; set; }
        public Nullable<long> DepotItems_id { get; set; }
        public Nullable<decimal> DepotCount { get; set; }
        public Nullable<long> ChangKu_ID { get; set; }
    
        public virtual Inventory_ChangKu Inventory_ChangKu { get; set; }
        public virtual Inventory_Company Inventory_Company { get; set; }
        public virtual Inventory_DepotItems Inventory_DepotItems { get; set; }
        public virtual Inventory_GongYingShang Inventory_GongYingShang { get; set; }
        public virtual ICollection<Inventory_Transaction> Inventory_Transaction { get; set; }
        public virtual ICollection<Inventory_Transaction> Inventory_Transaction1 { get; set; }
    }
}
