//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Transaction
    {
        public long ID { get; set; }
        public int AddUser { get; set; }
        public System.DateTime ApplyTime { get; set; }
        public long Int_Depot_ID { get; set; }
        public long OutDepot_ID { get; set; }
        public short Del { get; set; }
        public Nullable<short> ToExamine { get; set; }
        public Nullable<int> ToExamineUserID { get; set; }
        public int ZhuangTai { get; set; }
        public long BoolItems_ID { get; set; }
        public Nullable<decimal> TransInt { get; set; }
    
        public virtual Inventory_BoolItem Inventory_BoolItem { get; set; }
        public virtual Inventory_Depot Inventory_Depot { get; set; }
        public virtual Inventory_Depot Inventory_Depot1 { get; set; }
        public virtual Inventory_UserInfo Inventory_UserInfo { get; set; }
        public virtual Inventory_UserInfo Inventory_UserInfo1 { get; set; }
    }
}
