//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Login_list
    {
        public long id { get; set; }
        public int Userinfoid { get; set; }
        public string LoginIP { get; set; }
        public System.DateTime LoginTime { get; set; }
    
        public virtual Inventory_UserInfo Inventory_UserInfo { get; set; }
    }
}
