//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_GongYingShang
    {
        public Inventory_GongYingShang()
        {
            this.Inventory_Depot = new HashSet<Inventory_Depot>();
        }
    
        public long ID { get; set; }
        public string Number { get; set; }
        public string TextName { get; set; }
        public string Addess { get; set; }
        public string Photo { get; set; }
        public string PersonName { get; set; }
        public string Bak { get; set; }
        public short Del { get; set; }
    
        public virtual ICollection<Inventory_Depot> Inventory_Depot { get; set; }
    }
}
