//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Department
    {
        public Inventory_Department()
        {
            this.Inventory_ActionInfo = new HashSet<Inventory_ActionInfo>();
            this.Inventory_UserInfo = new HashSet<Inventory_UserInfo>();
        }
    
        public int ID { get; set; }
        public string DepName { get; set; }
        public int ParentId { get; set; }
        public string TreePath { get; set; }
        public int Level { get; set; }
        public bool IsLeaf { get; set; }
        public short DelFlag { get; set; }
    
        public virtual ICollection<Inventory_ActionInfo> Inventory_ActionInfo { get; set; }
        public virtual ICollection<Inventory_UserInfo> Inventory_UserInfo { get; set; }
    }
}
