//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Position
    {
        public Inventory_Position()
        {
            this.Inventory_UserInfo = new HashSet<Inventory_UserInfo>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public short Del { get; set; }
        public Nullable<int> Short { get; set; }
        public string Bak { get; set; }
    
        public virtual ICollection<Inventory_UserInfo> Inventory_UserInfo { get; set; }
    }
}
