//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Inventory_ActionInfo> Inventory_ActionInfo { get; set; }
        public DbSet<Inventory_BoolItem> Inventory_BoolItem { get; set; }
        public DbSet<Inventory_BumenInfoSet> Inventory_BumenInfoSet { get; set; }
        public DbSet<Inventory_ChangKu> Inventory_ChangKu { get; set; }
        public DbSet<Inventory_Company> Inventory_Company { get; set; }
        public DbSet<Inventory_Department> Inventory_Department { get; set; }
        public DbSet<Inventory_Depot> Inventory_Depot { get; set; }
        public DbSet<Inventory_DepotItems> Inventory_DepotItems { get; set; }
        public DbSet<Inventory_GongYingShang> Inventory_GongYingShang { get; set; }
        public DbSet<Inventory_Login_list> Inventory_Login_list { get; set; }
        public DbSet<Inventory_Position> Inventory_Position { get; set; }
        public DbSet<Inventory_R_UserInfo_ActionInfo> Inventory_R_UserInfo_ActionInfo { get; set; }
        public DbSet<Inventory_RoleInfo> Inventory_RoleInfo { get; set; }
        public DbSet<Inventory_Transaction> Inventory_Transaction { get; set; }
        public DbSet<Inventory_Userbak> Inventory_Userbak { get; set; }
        public DbSet<Inventory_UserInfo> Inventory_UserInfo { get; set; }
    }
}
